/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function plus(a: number, b: number): number
export type JsAlgo = Algo
export declare class Algo {
  constructor(name: string)
  hash(v: string): string
  getName(): string
}
export type JsMatrix = Matrix
export declare class Matrix {
  constructor(data: Array<Array<number>>)
  mul(other: Matrix): Matrix
  multiply(other: Array<Array<number>>): Matrix
  display(): string
}
